<?php

/**
 * @file
 * Provides core hooks for skipper_affinity module.
 */

use Drupal\Core\Session\AccountInterface;
use Drupal\skipper_affinity\SkipperAffinityEventSubscriber;

/**
 * Implements hook_user_logout().
 */
function skipper_affinity_user_logout(AccountInterface $account) {
  // Some cleanup if the user is logging out of the site.
  $request = \Drupal::request();
  if ($request->cookies->has(SkipperAffinityEventSubscriber::COOKIE_NAME)) {
    setcookie(SkipperAffinityEventSubscriber::COOKIE_NAME, '', 0, base_path());
  }
}
