<?php

/**
 * @file
 * Provides core hooks for skipper_affinity module.
 */

/**
 * Implements hook_init().
 */
function skipper_affinity_init() {
  if ((user_is_logged_in()) && ($_COOKIE["SKIPPER_AFFINITY"] != gethostname())) {
    setcookie('SKIPPER_AFFINITY', gethostname(), time() + (365 * 24 * 60 * 60), base_path());
  }
}

/**
 * Implementation of hook_user_logout().
 */
function skipper_affinity_user_logout($account) {
  if (isset($_COOKIE['SKIPPER_AFFINITY'])) {
    setcookie('SKIPPER_AFFINITY', '', 0, base_path());
  }
}
